server:  port: 80  
spring:  mvc:    static-path-pattern: /static/**
  profiles:
    active:
    - dev  janitor:    packages:      com.jhxapi.com    path:      interceptor:        /**      exclude:         /static/**